# Generated by Django 3.1.4 on 2020-12-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_pizza', models.CharField(choices=[('Regular', 'Regular'), ('Square', 'Square')], default='Regular', max_length=32)),
                ('Size_of_pizza', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra-Large', 'Extra-Large'), ('Party-Pizza', 'Party-Pizza')], default='Small', max_length=32)),
                ('Topping_of_pizza', models.CharField(choices=[('Onion', 'Onion'), ('Tomato', 'Tomato'), ('Corn', 'Corn'), ('Capsicum', 'Capsicum'), ('Cheese', 'Cheese'), ('Jalapeno', 'Jalapeno'), ('Sausage', 'Sausage'), ('Mushroom', 'Mushroom')], default='Onion', max_length=32)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
